# Gitlab CI/CD pipeline to generate documentation

stages:
  - test
  - build
  - deploy


# ###########################
# Test stage
# ###########################

pytest:
  image: python:3.6
  stage: test
  script:
    - pip install pytest pytest-cov
    - pip install -r requirements.txt
    - pip install -e ".[all]"
    - pytest --cov=pyxel --cov-report=
    - coverage report
  allow_failure: false

# ###########################
# Build stage
# ###########################

# Generate the Sphinx documentation into 'doc/html'
doc:
  image: python:3.6
  stage: build
  script:
    - pip install -r docs/requirements-docs.txt
    - pip install -r requirements.txt
    - pip install -e ".[all]"
    - pip install doc8
    - export PYTHONPATH=$PWD
    - doc8 docs/source
    - sphinx-build docs/source docs/html -E -a -j 4
    - python badges.py -doc="passed"
  artifacts:
    paths:
      - docs/html
      - documentation.svg
  allow_failure: false
  only:
    - master

website:
  image: alpine
  stage: build
  script:
    - wget https://esa.gitlab.io/pyxel-website/pyxel-website.tar.gz
    - tar -xzvf pyxel-website.tar.gz
    - ls html
  artifacts:
    paths:
       - html
  only:
    - master

# ###########################
# Deploy Stage
# ###########################

# Create the pages
pages:
  image: python:3.6
  stage: deploy
  script:
    - mkdir public
    - mv docs/html public/doc
    - mv html/* public
    - mv documentation.svg public
    - ls public
  artifacts:
    paths:
      - public
  allow_failure: false
  only:
    - master
