# Gitlab CI/CD pipeline to generate documentation

# ###########################
# Test stage
# ###########################

doc8:
  image: python:3.6
  stage: test
  script:
    - pip install sphinx doc8
    - doc8 docs/source
  allow_failure: false
  only:
    - master


# ###########################
# Build stage
# ###########################

# Generate the Sphinx documentation into 'doc/html'
doc:
  image: continuumio/anaconda3
  stage: build
  script:
#   - pip install docutils pygments
    - pip install -r docs/requirements-docs.txt
    - pip install -r requirements.txt
    - export PYTHONPATH=$PWD
    - sphinx-build docs/source docs/html -E -a -j 4
  artifacts:
    paths:
      - docs/html
#  cache:
#    key: "$CI_COMMIT_REF_NAME"
#    paths:
#      - docs/html
  allow_failure: false
  only:
    - master


# ###########################
# Deploy Stage
# ###########################

# Create the pages
pages:
  image: python:3.6
  stage: deploy
  script:
#    - pip install docutils pygments
    - mkdir public
    - mv docs/html public/doc
    - ls public
  artifacts:
    paths:
      - public
  allow_failure: false
  only:
    - master
