# Gitlab CI/CD pipeline to generate documentation

stages:
  - build
  - deploy

# ###########################
# Build stage
# ###########################

# Generate the Sphinx documentation into 'doc/html'
doc:
  image: python:3.6  # continuumio/anaconda3
  stage: build
  script:
    - pip install -r docs/requirements-docs.txt
    - pip install -r requirements.txt
    - pip install doc8
    - doc8 docs/source
#    - export PYTHONPATH=$PWD
    - sphinx-build docs/source docs/html -E -a -j 4
  artifacts:
    paths:
      - docs/html
  allow_failure: false
  only:
    - master


# ###########################
# Deploy Stage
# ###########################

# Create the pages
pages:
  image: python:3.6
  stage: deploy
  script:
    - mkdir public
    - mv docs/html public/doc
    - ls public
  artifacts:
    paths:
      - public
  allow_failure: false
  only:
    - master
