# ########################################################### #
# Pyxel detector simulation framework                         #
#                                                             #
# Example YAML configuration file                             #
# Exposure mode combining different detector effect models    #                         
# ########################################################### #


# yaml-language-server: $schema=https://esa.gitlab.io/pyxel/doc/latest/pyxel_schema.json
exposure:

  readout:
    times: [1.0]
    non_destructive:  false

  outputs:
    output_folder: "low_flux_07"
    save_data_to_file:
      - detector.image.array:   ['fits']
      - detector.pixel.array: ['npy']
    #save_exposure_data:
      #- dataset: ['nc']
      
ccd_detector:

  geometry:
    row: 1024               # pixel
    col: 1024               # pixel
    total_thickness: 20.    # um
    pixel_vert_size: 13.    # um
    pixel_horz_size: 13.    # um

  environment:
    temperature: 183        # K

  characteristics:
    quantum_efficiency: 0.7                 # -
    charge_to_volt_conversion: 1.4e-6      # V/e
    pre_amplification: 1                # V/V
    adc_voltage_range: [0, 0.1]
    adc_bit_resolution: 16
    full_well_capacity: 80000               # e
    


pipeline:
  # -> photon
  photon_collection:
    - name: load_image
      func: pyxel.models.photon_collection.load_image
      enabled: true
      arguments:
        image_file: 
        convert_to_photons: false
        multiplier: 1.0
        time_scale: 1.0
        bit_resolution: 16
        align: "center"

    - name: shot_noise
      func: pyxel.models.photon_collection.shot_noise
      enabled: false

    - name: optical_psf
      func: pyxel.models.photon_collection.optical_psf
      enabled: false
      arguments:
        fov_arcsec: 5 # FOV in arcseconds
        pixelscale: 0.01 #arcsec/pixel
        wavelength: 0.350e-6 # wavelength in meters
        optical_system:
          - item: CircularAperture
            radius: 3
        

  # photon -> charge
  charge_generation:
    - name: photoelectrons
      func: pyxel.models.charge_generation.simple_conversion
      enabled: true
# at 1 keV a single comsic ray will produce a signal close to that of dark current.... is it realistic? 
# This is also using a proton shielding file with 100x less flux 
# Original spectrum was found for near-earth orbit, during maximum solar activity      
    - name: cosmix
      func: pyxel.models.charge_generation.cosmix
      enabled: false
      arguments:
        simulation_mode: cosmic_ray
        running_mode: "stepsize"
        particle_type: proton
        initial_energy: 1          # MeV
        particles_per_second: 1
        incident_angles: [0,0]
        spectrum_file: 'C:/Users/akade/AppData/Roaming/Python/Python38/site-packages/pyxel/models/charge_generation/data/proton_L2_solarMax_11mm_Shielding_100x.txt'
    
      
    - name: charge_deposition
      func: pyxel.models.charge_generation.charge_deposition
      enabled: false
      arguments:
        flux: 100
        step_size: 1.
        energy_mean: 1.
        energy_spread: .1
        energy_spectrum: 'C:/Users/akade/AppData/Roaming/Python/Python38/site-packages/pyxel/models/charge_generation/data/proton_L2_solarMax_11mm_Shielding.txt'
        energy_spectrum_sampling: 'log'
        ehpair_creation: 3.6
        material_density: 2.33
        particle_direction: 'orthogonal'
        stopping_power_curve: 'C:/Users/akade/AppData/Roaming/Python/Python38/site-packages/pyxel/models/charge_generation/data/protons-in-silicon_stopping-power.csv'
    
    - name: dark_current
      func: pyxel.models.charge_generation.dark_current
      enabled: false
      arguments:
        figure_of_merit: 1.  # nA/cm^2
        band_gap: 1.26  # eV, optional
        band_gap_room_temperature: 1.26  # eV, optional
        spatial_noise_factor: 0.1
        temporal_noise: true
         
    - name: simple_dark_current
      func: pyxel.models.charge_generation.simple_dark_current
      enabled: true
      arguments:
        dark_rate: .0003
    
    
  # charge -> pixel
  charge_collection:
    - name: simple_collection
      func: pyxel.models.charge_collection.simple_collection
      enabled: true

    - name: full_well
      func: pyxel.models.charge_collection.simple_full_well
      enabled: true

  # pixel -> pixel
  charge_transfer:
    - name: EMCCD_poisson
      func: pyxel.models.charge_transfer.EMCCD_poisson.multiplication_register_CIC
      enabled: true
      arguments:
        singleStageProbability: .013
        stageCount: 604
        threshold: 0.004

  # pixel -> signal
  charge_measurement:
    - name: simple_measurement
      func: pyxel.models.charge_measurement.simple_measurement
      enabled: true
    - name: output_noise
      func: pyxel.models.charge_measurement.readout_noise.output_node_noise
      enabled: true
      arguments:
        std_deviation: 0.0000084
    - name: dc_offset
      func: pyxel.models.charge_measurement.dc_offset
      enabled: true
      arguments:
        offset: 0.002
        
  # signal -> image
  readout_electronics:
    - name: simple_amplifier
      func: pyxel.models.readout_electronics.simple_amplifier
      enabled: true
    - name: simple_adc
      func: pyxel.models.readout_electronics.simple_adc
      enabled: true
