#processor:
#  runner: pyxel_alpha.simulate_ccd
#  xx : pyxel.models.ccd_noise.CcdNoiseGenerator
#  pipeline : pyxel.detectors.ccd.CcdTransferFunction

#[pipeline_options]
#shot_noise: True
#fix_pattern_noise: True
#readout_noise: True


!CCD_PIPELINE
  doc: blah blah

  ccd: !CCD
#    photons: null
    photons: 10
    signal: null #!from_file ../data/HorseHead_orig.fits
    charge: null

    geometry:
      row: 100                      # compulsory
      col: 100                      # compulsory
      depletion_thickness: 10.0     # um
      field_free_thickness: 0.0     # um
      substrate_thickness: 0.0      # um
      pixel_ver_size: 10.0          # um
      pixel_hor_size: 10.0          # um

    environment:
      temperature: 320  # detector temperature Kelvin

    characteristics:
      k: 0            # camera gain constant in digital number (DN)
      j: 0            # camera gain constant in photon number
      qe: 0.5         # -
      eta: 1          # e/photon
      sv: 1.0e-6      # V/e
      accd: 0.8       # V/V
      a1: 100         # V/V
      a2: 65536       # DN/V
      fwc: 4500       # e (full well capacity)
      pix_non_uniformity: !from_file ../data/non_uniformity_array_normal_stdev0.03.data

  # -> photons
  optics: !models
    shot_noise: pyxel.models.ccd_noise.apply_shot_noise
#    ray_tracing: !class
#      name: pyxel.models.ccd_noise.OpticsModelRayTracer
#      args:
#        path: null
#    shot_noise: true
#    fixed_pattern_noise: false
#    ray_tracing: true
#    diffraction: false
#    other_model: false

  # photons -> compute_charge -> charge

  # -> charge
  charge_generation: !models
    fixed_pattern_noise: pyxel.models.ccd_noise.add_fix_pattern_noise
    tars: !function
      name: pyxel.models.ccd_noise.apply_tars
      kwargs:
        initial_energy: random  #100.0  # MeV
        particule_number: 1000
        incident_angles:      # rad
          - random  #0.31416  # pi / 10
          - random  #0.7853   # pi / 4
        starting_position:    # um
          - random  #500.0
          - random  #500.0
          - 0.0
        stepping_length: 1.0  # um

  # -> charge
  charge_collection: !models

  # -> charge
  charge_transfer: !models

  # -> signal
  charge_readout: !models
    readout_noise: !function
      name: pyxel.models.ccd_noise.add_readout_noise
      kwargs:
        readout_sigma: 1


#    - !Function
#        ref: pyxel.models.add_shot_noise
#        args:
#          - self.ccd.p
#
#    - !Method
#        ref: compute
#        obj: self
#        args:
#          - CCD.photons
#
##    - !shot_noise
#    - !OPTICS_MODEL
#        name: shot_noise
#        func: CCDNoiseGenerator.add_shot_noise
#        params:
#          sss,,s


#    geometry:
#      row: 0                # compulsory
#      col: 0                # compulsory
#      depletion_zone: 0
#      field_free_zone: 0    # opt.
#      sub_thickness: 0      # opt.
#      pix_ver_size: 0       # opt.
#      pix_hor_size: 0       # opt.

    # compulsory
#    transfer_function_parameters:
#      k: 0
#      j: 0
#      qe: 0
#      eta: 0
#      sv: 0
#      accd: 0
#      a1: 0
#      a2: 0
#      fwc: 0
#      temperature: 0


#  # photons -> photons
#  optics:
#    - !shot_noise
#    - !OPTICS_MODEL
#        func: CCDNoiseGenerator.add_shot_noise
#        params:
#          sss,,s
#
#  # photons -> electrons
#  charge_generation:
#    # !compute_charge(qe, eta)
#    params:
#      qe: 0
#      eta: 0
#    extra_models:
#      - !fixed_pattern_noise #(opt)
#        noise_filename: none  # 2d array
##      - !tars
##        depletion_zone: 0
##        field_free_zone: 0
##        sub_thickness: 0
##        pix_ver_size: 0
##        pix_hor_size: 0
#      - !super_fancy_model
##        depletion_zone: 0.0
#
#  # electrons -> electrons
#  charge_collection:
#    # !charge_excess
#    params:
#      fwc: 0
#
#  # electrons -> electrons
#  charge_transfer:
#
#  # electrons -> ADU
#  charge_readout:
#    # !compute_signal
#    params:
#      sv: 0
#      accd: 0
#      a1: 0
#      a2: 0
#    extra_models:
#      - !add_readout_noise (opt)
#        sigma_readout: 0
#
