#processor:
#  runner: pyxel_alpha.simulate_ccd
#  xx : pyxel.models.ccd_noise.CcdNoiseGenerator
#  pipeline : pyxel.detectors.ccd.CcdTransferFunction

process: !PROCESSOR

  detector: !CCD
    photons: 100
    image: null   # !from_file data/HorseHead_orig.fits

    geometry: !geometry
      row: 100                      # compulsory
      col: 100                      # compulsory
      total_thickness: 10.0         # um
      depletion_thickness: 10.0     # um
      field_free_thickness: 0.0     # um
      pixel_vert_size: 10.0         # um
      pixel_horz_size: 10.0         # um
      material: 'silicon'
      n_acceptor: 0.0               # cm-3
      n_donor: 0.0                  # cm-3
      bias_voltage: 0.0             # V

    environment: !environment
      temperature: 300                    # Kelvin, detector temperature
      total_ionising_dose: 8.0e11         # total ionising dose (IEL)
      total_non_ionising_dose: 8.0e11     # total non-ionising dose (NIEL)

    characteristics: !ccd_characteristics
      qe: 0.5               # -
      eta: 1                # e/photon
      sv: 1.0e-6            # V/e
      accd: 0.8             # V/V
      a1: 100               # V/V
      a2: 65536             # DN/V
      fwc_parallel: 20000   # e
      fwc_serial: 30000     # e

  pipeline: !CCD_PIPELINE
    # -> photons
    optics: !models
      shot_noise: !function
        name: pyxel.models.ccd_noise.add_shot_noise
  #    ray_tracing: !class
  #      name: pyxel.models.ccd_noise.OpticsModelRayTracer
  #      args:
  #        path: null

    # photons -> compute_charge -> charge

    # -> charge
    charge_generation: !models
      photoelectrons: pyxel.models.photoelectrons.simple_conversion
      tars: !function
        name: pyxel.models.tars.tars.run_tars
        kwargs:
          initial_energy: 100.0   # MeV
          particle_number: 10
          incident_angles:      # rad
            - random # 0.31416  # pi / 10
            - random # 0.7853   # pi / 4
          starting_position:    # um
            - random # 500.0
            - random # 500.0
            - 0.0
          stepping_length: 1.0  # um

    # -> charge
    charge_collection: !models
#      fixed_pattern_noise: !function
#        name: pyxel.models.ccd_noise.add_fix_pattern_noise
#        kwargs:
#          pix_non_uniformity: !from_file data/non_uniformity_array_normal_stdev0.03.data

#      diffusion: !function
#        name: pyxel.models.diffusion.diffusion
##        kwargs:

#      full_well: !function
#        name: pyxel.models.full_well.simple_pixel_full_well
#        kwargs:
#          fwc: 10000       # e (full well capacity)  # if defined use this, if not use the default parameter from characteristics

    # -> charge
    charge_transfer: !models
      cdm: !function
        name: pyxel.models.cdm.CDM.cdm
        kwargs:
#         vth: 1.168e7
         beta_p: 0.6
         beta_s: 0.6
         vg: 6.e-11
         svg: 1.0e-10
         t: 20.48e-3
         st: 5.0e-6
         parallel_trap_file: pyxel/models/cdm/cdm_euclid_parallel.dat
         serial_trap_file: null   # pyxel/models/cdm/cdm_euclid_serial.dat

    # -> signal
    charge_measurement: !models
#      readout_noise: !function
#        name: pyxel.models.ccd_noise.add_output_node_noise
#        kwargs:
#          std_deviation: 1.0

    # -> signal
    readout_electronics: !models
