#processor:
#  runner: pyxel_alpha.simulate_ccd
#  xx : pyxel.models.ccd_noise.CcdNoiseGenerator
#  pipeline : pyxel.detectors.ccd.CcdTransferFunction

process: !PROCESSOR

  detector: !CMOS
    geometry: !geometry
      row: 150                      # compulsory
      col: 200                      # compulsory
      total_thickness: 10.0         # um
      depletion_thickness: 10.0     # um
      field_free_thickness: 0.0     # um
      pixel_vert_size: 10.0         # um
      pixel_horz_size: 10.0         # um
      material: 'silicon'
      n_acceptor: 0.0               # cm-3
      n_donor: 0.0                  # cm-3
      bias_voltage: 0.0             # V
      n_output: 4
      n_row_overhead: 0
      n_frame_overhead: 0
      reverse_scan_direction: False
      reference_pixel_border_width: 4

    environment: !environment
      temperature: 320  # detector temperature Kelvin

    characteristics: !cmos_characteristics
      qe: 0.5         # -
      eta: 1          # e/photon
      sv: 1.0e-6      # V/e
      amp: 0.8       # V/V
      a1: 100         # V/V
      a2: 65536       # DN/V
      fwc: 20000   # e

  pipeline: !CMOS_PIPELINE

    photon_generation: !models
      load_image: !model
        name: pyxel.models.photon_generation.load_image
        enabled: true
        arguments:
          image_file: data/HorseHead_orig.fits

      photon_level: !model
        name: pyxel.models.photon_generation.add_photon_level
        enabled: false
        arguments:
          level: 100

    # -> photons
    optics: !models
#      shot_noise: !function
#        name: pyxel.models.ccd_noise.add_shot_noise

    # -> charge
    charge_generation: !models
      photoelectrons: !model
        name: pyxel.models.photoelectrons.simple_conversion

      tars: !model
        name: pyxel.models.tars.tars.run_tars
        arguments:
          initial_energy: 100.0   # MeV
          particle_number: 10
          incident_angles:      # rad
            - random # 0.31416  # pi / 10
            - random # 0.7853   # pi / 4
          starting_position:    # um
            - random # 500.0
            - random # 500.0
            - 0.0
          stepping_length: 1.0  # um

    # -> charge
    charge_collection: !models
#      fixed_pattern_noise: !function
#        name: pyxel.models.ccd_noise.add_fix_pattern_noise
#        arguments:
#          pix_non_uniformity: !from_file data/non_uniformity_array_normal_stdev0.03.data
      diffusion: !model
        name: pyxel.models.diffusion.diffusion
#        arguments:
      full_well: !model
        name: pyxel.models.full_well.simple_pixel_full_well
        arguments:
          fwc: 100       # e (full well capacity)

    # -> signal
    charge_measurement: !models
#      readout_noise: !function
#        name: pyxel.models.ccd_noise.add_output_node_noise
#        arguments:
#          std_deviation: 1.0

   # -> signal
    signal_transfer: !models

      nghxrg_read: !model
        name: pyxel.models.nghxrg.nghxrg.white_read_noise
        arguments:
          rd_noise: 400.           # White read noise per integration
          ref_pixel_noise_ratio: 80.
          window_mode: WINDOW
          wind_x0: 50
          wind_y0: 100
          wind_x_size: 200
          wind_y_size: 200

      nghxrg_pca_zero: !model
        name: pyxel.models.nghxrg.nghxrg.pca_zero_noise
        arguments:
          pca0_amp: 450.           # Amplitude of PCA zero "picture frame" noise
          window_mode: WINDOW
          wind_x0: 300
          wind_y0: 100
          wind_x_size: 200
          wind_y_size: 200

      nghxrg_c_pink: !model
        name: pyxel.models.nghxrg.nghxrg.corr_pink_noise
        arguments:
          c_pink: 300.             # Correlated pink noise
          window_mode: WINDOW
          wind_x0: 550
          wind_y0: 100
          wind_x_size: 200
          wind_y_size: 200

      nghxrg_u_pink: !model
        name: pyxel.models.nghxrg.nghxrg.uncorr_pink_noise
        arguments:
          u_pink: 200.             # Uncorrelated pink noise
          window_mode: WINDOW
          wind_x0: 50
          wind_y0: 350
          wind_x_size: 200
          wind_y_size: 200

      nghxrg_acn: !model
        name: pyxel.models.nghxrg.nghxrg.acn_noise
        arguments:
          acn: 500.                 # Correlated ACN
          window_mode: WINDOW
          wind_x0: 300
          wind_y0: 350
          wind_x_size: 200
          wind_y_size: 200

      nghxrg_ktc_bias: !model
        name: pyxel.models.nghxrg.nghxrg.ktc_bias_noise
        arguments:
          ktc_noise: 500.
          bias_offset: 300.
          bias_amp: 400.
          window_mode: WINDOW
          wind_x0: 550
          wind_y0: 350
          wind_x_size: 200
          wind_y_size: 200

    # -> signal
    readout_electronics: !models
