
parametric:
#  mode: single
#  mode: embedded
  mode: sequential
  steps:
    -
      enabled: true
      key: pipeline.photon_generation.photon_level.arguments.level
      values: [10, 20, 30]
    -
      enabled: true
      key: pipeline.charge_generation.tars.arguments.initial_energy
      values: [100, 200, 300]
    -
      enabled: false
      key:
      values:
    -
      enabled: false
      key:
      values:

ccd_process:

  detector:

    geometry:
      row: 100                      # compulsory
      col: 100                      # compulsory
      total_thickness: 10.0         # um
      depletion_thickness: 10.0     # um
      field_free_thickness: 0.0     # um
      pixel_vert_size: 10.0         # um
      pixel_horz_size: 10.0         # um
      material: 'silicon'
      n_acceptor: 0.0               # cm-3
      n_donor: 0.0                  # cm-3
      bias_voltage: 0.0             # V

    environment:
      temperature: 300                    # Kelvin, detector temperature
      total_ionising_dose: 8.0e11         # total ionising dose (IEL)
      total_non_ionising_dose: 8.0e11     # total non-ionising dose (NIEL)

    characteristics:
      qe: 0.5               # -
      eta: 1                # e/photon
      sv: 1.0e-6            # V/e
      amp: 0.8             # V/V
      a1: 100               # V/V
      a2: 65536             # DN/V
      fwc: 20000            # e
      fwc_serial: 30000     # e

  pipeline:

    photon_generation:
      load_image:
        name: pyxel.models.photon_generation.load_image
        enabled: false
        arguments:
          image_file: null

      photon_level:
        name: pyxel.models.photon_generation.add_photon_level
        enabled: true
        arguments:
          level: 100

      shot_noise:
        name: pyxel.models.photon_generation.add_shot_noise
        enabled: true

    # -> photons
    optics:

    # -> charge
    charge_generation:
      photoelectrons:
        enabled: false
        name: pyxel.models.photoelectrons.simple_conversion

      tars:
        name: pyxel.models.tars.tars.run_tars
        enabled: true
        arguments:
          initial_energy: 100.0   # MeV
          particle_number: 10
          incident_angles:      # rad
            - random # 0.31416  # pi / 10
            - random # 0.7853   # pi / 4
          starting_position:    # um
            - random # 500.0
            - random # 500.0
            - 0.0
          stepping_length: 1.0  # um

    # -> charge
    charge_collection:
      fixed_pattern_noise:
        enabled: false
        name: pyxel.models.ccd_noise.add_fix_pattern_noise
        arguments:
          pix_non_uniformity: data/non_uniformity_array_normal_random_dist.data

      diffusion:
        enabled: false
        name: pyxel.models.diffusion.diffusion
#        arguments:

      full_well:
        name: pyxel.models.full_well.simple_pixel_full_well
        enabled: false
        arguments:
          fwc: 100       # e  # if defined use this, if not use the default parameter from characteristics

    # -> charge
    charge_transfer:
      cdm:
        enabled: false
        name: pyxel.models.cdm.CDM.cdm
        arguments:
         beta_p: 0.6
         beta_s: 0.6
         vg: 6.e-11
         svg: 1.0e-10
         t: 20.48e-3
         st: 5.0e-6
         parallel_trap_file: pyxel/models/cdm/cdm_euclid_parallel.dat
         serial_trap_file: pyxel/models/cdm/cdm_euclid_serial.dat

    # -> signal
    charge_measurement:
      readout_noise:
        enabled: false
        name: pyxel.models.ccd_noise.add_output_node_noise
        arguments:
          std_deviation: 1.0

    # -> signal
    readout_electronics:
