baseURL: "https://esa.gitlab.io/pyxel/"
languageCode: "en-us"

title: "Pyxel"
description: "description"
theme: "beautifulhugo"
lastmod: "2019-06-14"

Params:
  subtitle: "A general simulation framework in Python for astronomical imaging detectors"
  logo: img/pyxel-logo.png  # Expecting square dimensions
  # favicon: img/favicon.ico    # todo
  commit: false
  rss: true
  comments: true
  readingTime: false
  wordCount: false
  useHLJS: true
  socialShare: true
  delayDisqus: true
  showRelatedPosts: true

Author:
  name: David Lucsanyi
#  website: yourwebsite.com
  email: david.lucsanyi@esa.int
  gitlab: esa/pyxel
#  linkedin: "david-lucsanyi"    # todo: not working with chrome
#  twitter: username

menu:
  main:
    -
      name: News
      url:
      weigth: 1
    -
      name: About
      url: page/about/
      weight: 2
    -
      name: Documentation
      url: doc
      weight: 3
    -
      name: Download
      url: tags
      weigth: 4