baseURL: "https://esa.gitlab.io/pyxel/"
languageCode: "en-us"

title: "PyXEL"
description: "description"
theme: "beautifulhugo"

Params:
  subtitle: "a subtitle"
  logo: img/pyxel-logo.png  # Expecting square dimensions
  # favicon: img/favicon.ico
  commit: false
  rss: true
  comments: true
  readingTime: true
  wordCount: true
  useHLJS: true
  socialShare: true
  delayDisqus: true
  showRelatedPosts: true

Author:
  name: David Lucsanyi
  website: yourwebsite.com
  email: david.lucsanyi@esa.int
  gitlab: esa/pyxel
  # twitter: username

menu:
  main:
    -
      name: Blog
      url: ""
      weigth: 2
    -
      name: About
      url: page/about/
      weight: 3
    -
      name: Docs
      title: Docs
      url: doc
      weight: 1
    -
      name: Tags
      url: tags
      weigth: 3