baseURL: "http://example.org/"
languageCode: "en-us"

title: "PyXEL"
description: "description"
theme: "beautifulhugo"

Params:
  subtitle: "a subtitle"
  logo: img/pyxel-logo.png  # Expecting square dimensions
  # favicon: img/favicon.ico
  commit: false
  rss: true
  comments: true
  readingTime: true
  wordCount: true
  useHLJS: true
  socialShare: true
  delayDisqus: true
  showRelatedPosts: true

Author:
  name: John Doe
  website: yourwebsite.com
  email: youremail@domain.com
  gitlab: username
  twitter: username

menu:
  main:
    -
      name: Blog
      url: ""
      weigth: 1
    -
      name: About
      url: page/about/
      weight: 3
    -
      name: XXX
      title: Foo
      url: post/2019-05-28-first_post
      weight: 1
    -
      name: Tags
      url: tags
      weigth: 3