baseURL: "https://esa.gitlab.io/pyxel/"
languageCode: "en-us"
relativeURLs: true

title: "Pyxel"
description: "simulation framework"
theme: "beautifulhugo"
lastmod: "2019-06-19"

Params:
  subtitle: "A general simulation framework in Python for astronomical and Earth observation imaging detectors"
  logo: img/pyxel-logo.png  # Expecting square dimensions
  favicon: img/pyxel-logo.png
  commit: false
  rss: true
  comments: true
  readingTime: false
  wordCount: false
  useHLJS: true
  socialShare: true
  delayDisqus: true
  showRelatedPosts: true

Author:
  name: David Lucsanyi
  website: http://sci.esa.int/pyxel
  email: pyxel@esa.int
  gitlab: esa/pyxel


menu:
  main:
    - name: News
      url: ..
      weight: 10

    - name: About
      identifier: about
      weight: 20
    - name: Introduction
      parent: about
      url: ../page/introduction/
      weight: 1
    - name: How it works
      parent: about
      url: ../page/pipeline/
      weight: 2
    - name: Features
      parent: about
      url: ../page/features/
      weight: 3
    - name: Models
      parent: about
      url: ../page/models/
      weight: 4
#    - name: Examples
#      parent: about
#      url: ../page/examples/
#      weight: 5

    - name: Community
      identifier: community
      weight: 30
    - name: Users
      parent: community
      url: ../page/community/
      weight: 1
    - name: Developers
      parent: community
      url: ../page/community/
      weight: 2
#    - name: Forum
#      parent: community
#      url: ..              # TODO
#      weight: 3
#    - name: Mailing list
#      parent: community
#      url: ..               # TODO
#      weight: 4
#    - name: F.A.Q.
#      parent: community
#      url: ../page/faq/
#      weight: 5
    - name: Links
      parent: community
      url: ../page/links/
      weight: 6

    - name: Documentation
      url: ../doc
      weight: 40

    - name: Download
      identifier: download
      weight: 50
    - name: Beta release
      parent: download
      url: ../page/releases/
      weight: 1
#    - name: Docker
#      parent: download
#      url: ../page/docker/
#      weight: 2
    - name: Repository
      parent: download
      url: http://gitlab.com/esa/pyxel
      weight: 3
#    - name: Issues
#      parent: download
#      url: http://gitlab.com/esa/pyxel/issues
#      weight: 4