#baseURL: "https://esa.gitlab.io/pyxel/"
baseURL: "https://esa.gitlab.io/pyxel/"
languageCode: "en-us"

title: "Pyxel"
description: "description"
theme: "beautifulhugo"
lastmod: "2019-06-14"

Params:
  subtitle: "A general simulation framework in Python for astronomical imaging detectors"
  logo: img/pyxel-logo.png  # Expecting square dimensions
  # favicon: img/favicon.ico    # todo
  commit: false
  rss: true
  comments: true
  readingTime: false
  wordCount: false
  useHLJS: true
  socialShare: true
  delayDisqus: true
  showRelatedPosts: true

Author:
  name: David Lucsanyi
#  website: yourwebsite.com
  email: david.lucsanyi@esa.int
  gitlab: esa/pyxel
#  linkedin: "david-lucsanyi"    # todo: not working with chrome
#  twitter: username

menu:
  main:
    - name: News
      url:


    - name: About
      identifier: about
    - name: Introduction
      parent: about
      url: page/introduction/
    - name: Examples
      parent: about
      url: page/examples/
    - name: Models
      parent: about
      url: page/models/
    - name: Quickstart
      parent: about
      url: page/quickstart/
    - name: Tutorials
      parent: about
      url: page/tutorials/


    - name: Community
      identifier: community
    - name: Users & Developers
      parent: community
      url: page/community/
#      weigth: -2
    - name: Forum
      parent: community
      url:                # TODO
#      weigth: -3
    - name: Mailing list
      parent: community
      url:                # TODO
#      weigth: -1
    - name: F.A.Q.
      parent: community
      url: page/faq/
#      weigth: -1


    - name: Documentation
      url: doc


    - name: Download
      identifier: download
    - name: Releases
      parent: download
      url: page/releases/
    - name: Repository
      parent: download
      url: http://gitlab.com/esa/pyxel
    - name: Docker
      parent: download
      url: page/docker/
#    - name: Issues
#      parent: download
#      url: http://gitlab.com/esa/pyxel/issues