from . import Characteristics

class CCDCharacteristics(Characteristics):
    def __init__(
        self, fwc_serial: int = ..., svg: float = ..., t: float = ..., st: float = ...
    ): ...
    fwc_serial: int = ...
    svg : float = ...
    t : float = ...
    st : float = ...
