from . import Characteristics

class CCDCharacteristics(Characteristics):
    def __init__(
        self, fwc_serial: int = 0, svg: float = 0.0, t: float = 0.0, st: float = 0.0
    ): ...
    @property
    def fwc_serial(self) -> int: ...
    @property
    def svg(self) -> float: ...
    @property
    def t(self) -> float: ...
    @property
    def st(self) -> float: ...
