from . import Characteristics

class CCDCharacteristics(Characteristics):
    def __init__(
        self, fwc_serial: int = ..., svg: float = ..., t: float = ..., st: float = ...
    ): ...
    @property
    def fwc_serial(self) -> int: ...
    @property
    def svg(self) -> float: ...
    @property
    def t(self) -> float: ...
    @property
    def st(self) -> float: ...
