class Characteristics:
    def __init__(
        self,
        qe: float = ...,
        eta: float = ...,
        sv: float = ...,
        amp: float = ...,
        a1: float = ...,
        a2: float = ...,
        fwc: int = ...,
        vg: float = ...,
        dt: float = ...,
    ): ...
    @property
    def qe(self) -> float: ...
    @property
    def eta(self) -> float: ...
    @property
    def sv(self) -> float: ...
    @property
    def amp(self) -> float: ...
    @property
    def a1(self) -> float: ...
    @property
    def a2(self) -> float: ...
    @property
    def fwc(self) -> float: ...
    @property
    def vg(self) -> float: ...
    @property
    def dt(self) -> float: ...
