class Characteristics:
    def __init__(
        self,
        qe: float = 0.0,
        eta: float = 0.0,
        sv: float = 0.0,
        amp: float = 0.0,
        a1: float = 0.0,
        a2: float = 0.0,
        fwc: int = 0,
        vg: float = 0.0,
        dt: float = 0.0,
    ): ...
    @property
    def qe(self) -> float: ...
    @property
    def eta(self) -> float: ...
    @property
    def sv(self) -> float: ...
    @property
    def amp(self) -> float: ...
    @property
    def a1(self) -> float: ...
    @property
    def a2(self) -> float: ...
    @property
    def fwc(self) -> float: ...
    @property
    def vg(self) -> float: ...
    @property
    def dt(self) -> float: ...
