from . import Characteristics

class CMOSCharacteristics(Characteristics):
    def __init__(
        self,
        cutoff: float = ...,
        vbiaspower: float = ...,
        dsub: float = ...,
        vreset: float = ...,
        biasgate: float = ...,
        preampref: float = ...,
    ): ...
    cutoff: float = ...
    vbiaspower: float = ...
    dsub: float = ...
    vreset: float = ...
    biasgate: float = ...
    preampref: float = ...
