class Environment:
    def __init__(
        self,
        temperature: float = ...,
        total_ionising_dose: float = ...,
        total_non_ionising_dose: float = ...,
    ): ...
    @property
    def temperature(self) -> float: ...
    @property
    def total_ionising_dose(self) -> float: ...
    @property
    def total_non_ionising_dose(self) -> float: ...
