class Environment:
    def __init__(
        self,
        temperature: float = ...,
        total_ionising_dose: float = ...,
        total_non_ionising_dose: float = ...,
    ): ...
    temperature: float = ...
    total_ionising_dose: float = ...
    total_non_ionising_dose: float = ...

