class Geometry:
    def __init__(
        self,
        row: int = ...,
        col: int = ...,
        total_thickness: float = ...,
        pixel_vert_size: float = ...,
        pixel_horz_size: float = ...,
    ): ...
    row: int = ...
    col: int = ...
    total_thickness: float = ...
    pixel_vert_size: float = ...
    pixel_horz_size: float = ...
    horz_dimension: float = ...
    vert_dimension: float = ...
