class Geometry:
    def __init__(
        self,
        row: int = 0,
        col: int = 0,
        total_thickness: float = 0.0,
        pixel_vert_size: float = 0.0,
        pixel_horz_size: float = 0.0,
    ): ...
    @property
    def row(self) -> int: ...
    @property
    def col(self) -> int: ...
    @property
    def total_thickness(self) -> float: ...
    @property
    def pixel_vert_size(self) -> float: ...
    @property
    def pixel_horz_size(self) -> float: ...
    @property
    def horz_dimension(self) -> float: ...
    @property
    def vert_dimension(self) -> float: ...
