# Create a new conda environment:
#   $ cd pyxel
#   $ conda update -n base conda
#   $ conda deactivate
#   $ conda env create -f continuous_integration/environment.yml
#   $ conda activate pyxel-dev
#   (pyxel_dev) $ pip install --no-deps -e .

# Get a list of all the environments:
#  $ conda env list -v

# Upgrade a conda environment
#  $ conda env update -f environment.yml [-n CONDA_ENV_NAME]
#  $ conda env update [-n CONDA_ENV_NAME] --all

# Remove a conda environment
#  $ conda env remove --name MYENV


name: pyxel-dev
channels:
  - conda-forge
dependencies:
# Python
  - python
  - pip
# Scientific computing
  - numba
  - numpy>=1.20
  - pandas
  - scipy
  - xarray>=0.19
# Plotting
  - matplotlib>=3.1
  - seaborn
  - holoviews>=1.14.2
  - bokeh
# Parallel computing
  - dask>=2.9
  - dask-labextension
# Jupyter notebook
  - ipywidgets>=7.5
  - jupyterlab
# Input/Output
  - astropy>=4.3
  - fsspec>=2021
  - h5py
  - pyyaml
  - xlrd
  - openpyxl
  - netcdf4
  - asdf
# Others
  - attrs
  - click
  - tqdm
  - typing-extensions
  - pygmo>=2.16.1
  - pympler
  - pillow
  - scikit-image
# Code formatting
  - black>=20
  - isort>=5
  - jupyterlab_code_formatter
# Documentation
  - doc8
  - sphinx
  - sphinx-book-theme
  - sphinxcontrib-bibtex
  - sphinx-panels
  - sphinx-inline-tabs
  - myst-nb
  - sphinx-copybutton
#  - jupyter-book
# Development
  - flake8
  - mypy
  - pre-commit
  - pytest
  - pytest-httpserver
  - tox
  - tryceratops
  - freezegun
  - codespell
# Pip packages
  - pip:
#    - --no-deps
    - poppy>=1.0.2

