# Conda environment for Pyxel version 1.12
# Install:    conda env create -f pyxel-1.12-environment.yaml
# Activate:   conda activate pyxel-1.12
# Deactivate: conda deactivate

# Upgrade:    conda update -f pyxel-1.12-environment.yaml
# Remove:     conda remove -n pyxel-1.12 --all
# List envs:  conda env list

name: pyxel-1.12

channels:
  - conda-forge
dependencies:
  - pyxel-sim=1.12
  - python=3.11
  - pip
  - ipykernel!=6.18.0   # Version 6.18.0 is not working
  - poppy>=1.1.0
# Optional packages
  - jupyterlab          # Install JupyterLab
  - dask-labextension   # Install an extension for JupyterLab
  - ipympl              # Interactive Matplotlib in Jupyter
# Pip packages
  - pip:
    - lacosmic
