# Conda environment for Pyxel version 1.4
# Install:    conda env create -f pyxel-1.4-environment.yaml
# Activate:   conda activate pyxel-1.4
# Deactivate: conda deactivate

# Upgrade:    conda update -f pyxel-1.4-environment.yaml
# Remove:     conda remove -n pyxel-1.4

name: pyxel-1.4

channels:
  - conda-forge

dependencies:
  - pyxel-sim=1.4
  - pip
# Optional packages
  - jupyterlab          # Install JupyterLab
  - dask-labextension   # Install an extension for JupyterLab
# Pip packages
  - pip:
    - poppy>=1.0.2
