################
# Pyxel - YAML configuration file for CCD detectors
# by David Lucsanyi
################

simulation:
###################
  mode: single
#  mode: parametric
#  mode: calibration
#######1############

  parametric_analysis:
    parametric_mode: sequential
#    parametric_mode: embedded
    steps:
      -
        enabled: true
        key: pipeline.photon_generation.photon_level.arguments.level
        values: [10, 20]

  calibration:
    calibration_mode: pipeline  # single_model
    arguments:
      target_data: 'C:/dev/work/cdm/data/better-plato-target-data/'
      target_fit_range: [51, 401]
      output_fit_range: [1103, 1453]
      weighting_func:
      generations: 3
      population_size: 10

      model_names: ['cdm', 'tars']
      variables: [['tr_p', 'nt_p', 'sigma_p', 'beta_p'], ['initial_energy']]
      var_log: [[True, True, True, False], [False]]
      var_arrays: [[True, True, True, False], [False]]
      params_per_variable: [[4, 4, 4, 1], [1]]
      lower_boundary: [[1.e-3, 1.e-2, 1.e-20, 0.], [1.]]
      upper_boundary: [[2., 1.e+1, 1.e-15, 1.], [10.]]

processor:
  class: pyxel.pipelines.processor.Processor

  detector:
    class: pyxel.detectors.ccd.CCD

    geometry:
      class: pyxel.detectors.ccd_geometry.CCDGeometry
      row:   2000
      col:   2000
      total_thickness: 40.0              # um
      depletion_thickness: 0.0           # um
      field_free_thickness: 0.0          # um
      pixel_vert_size: 10.               # um
      pixel_horz_size: 10.               # um
      readout_nodes: 1

    material:
      class: pyxel.detectors.material.Material
      material: 'silicon'
      n_acceptor: 0.0                    # cm-3
      n_donor: 0.0                       # cm-3

    environment:
      class: pyxel.detectors.environment.Environment
      temperature: 300                   # K
      total_ionising_dose: 1e+8          # MeV/g
      niel: 2.e+5                        # MeV/g

    characteristics:
      class: pyxel.detectors.ccd_characteristics.CCDCharacteristics
      qe: 0.5                            # -
      eta: 0.5                           # e/photon
      sv: 1.0e-6                         # V/e
      amp: 1.                            # V/V
      a1: 100                            # V/V
      a2: 65536                          # DN/V
      fwc: 2800                          # e
      fwc_serial: 3000                   # e
      bias_voltage: 50.0                 # V


  pipeline:
    class: pyxel.pipelines.ccd_pipeline.CCDDetectionPipeline


    # -> photons
    photon_generation:
      -
        name: load_image
        func: pyxel.models.photon_generation.load_image
        enabled: false
        arguments:
          image_file: data/055.fits
      -
        name: photon_level
        func: pyxel.models.photon_generation.add_photon_level
        enabled: false
        arguments:
          level: 0
      -
        name: shot_noise
        func: pyxel.models.photon_generation.add_shot_noise
        enabled: false

    # photons -> photons
    optics:

    # photons -> charge
    charge_generation:
      -
        name: photoelectrons
        func: pyxel.models.photoelectrons.simple_conversion
        enabled: true
      -
        name: tars
        func: pyxel.models.tars.tars.run_tars
        enabled: true
        arguments:
          simulation_mode: cosmic_ray
          running_mode: stepsize  # stopping  # geant4
          particle_type: proton   # ion  # electron
          initial_energy: random            # MeV
          particle_number: 100
          incident_angles:                  # rad
          starting_position:                # um
          spectrum_file: 'pyxel/models/tars/data/inputs/proton_L2_solarMax_11mm_Shielding.txt'

    # charge -> pixel
    charge_collection:
      -
        name: fixed_pattern_noise
        func: pyxel.models.ccd_noise.add_fix_pattern_noise
        enabled: false
        arguments:
          pix_non_uniformity: data/non_uniformity_array_normal_random_dist.data
      -
        name: full_well
        func: pyxel.models.full_well.simple_pixel_full_well
        enabled: false

    # pixel -> pixel
    charge_transfer:
      -
        name: cdm
        func: pyxel.models.cdm.CDM.cdm
        enabled: true
        arguments:
         beta_p: 0.6
         beta_s: 0.6
         vg: 6.e-11
         svg: 1.0e-10
         t: 20.48e-3
         st: 5.0e-6
         parallel_trap_file: pyxel/models/cdm/cdm_euclid_parallel.dat
         serial_trap_file: pyxel/models/cdm/cdm_euclid_serial.dat

    # pixel -> signal
    charge_measurement:
      -
        name: output_node_noise
        func: pyxel.models.ccd_noise.add_output_node_noise
        enabled: true
        arguments:
          std_deviation: 1000.

    # signal -> image
    readout_electronics: