################
# Pyxel configuration file for TESTING, EXPERIMENTING
# David Lucsanyi
################

simulation:
  mode: dynamic

  dynamic:
    non_destructive_readout:  true
    t_steps: 5
    t_start: 1.
    t_end: 10.

  outputs:
    output_folder:  'outputs'
    save_to_file:
      - detector.image.array:   [fits]
#      - detector.signal.array:  [npy, txt]
      - detector.charge.frame:  [csv]
#      - detector.photon.array:
#      - detector:               [hdf]


cmos_detector:

  geometry:
    row:   100                   #
    col:   100                   #
    total_thickness: 40.         # um
    pixel_vert_size: 10.         # um
    pixel_horz_size: 10.         # um

  material:
    material: silicon
    trapped_charge: data/cmos_trapped_charge.npy

  environment:
    temperature: 200.

  characteristics:
    qe: 0.5                 # -
    eta: 1.                 # e/photon
    sv: 3e-6                # V/e
    amp: 10.                # V/V
    a1: 100.                # V/V
    a2: 10000               # DN/V
    fwc: 1000000            # e
    # Adding new characteristics gives a detector.characteristics as None
    # bug in photoelectrons.py where ch.qe doesn't exist with a NoneType object...
    # Solution need to change cmos_characteristics.py to include those variable
    # and their range
    cutoff: 2.5                  # um
    vbiaspower: 3.350        # V
    dsub: 0.500              # V
    vreset: 0.250            # V
    biasgate: 2.300          # V
    preampref: 1.700         # V Reference voltage for the preamp [VRefMain for ASIC]


pipeline:

  # photon -> photon
  photon_generation:

    - name: illumination
      func: pyxel.models.photon_generation.illumination.illumination
      enabled: true
      arguments:
        level: 100
        option: elliptic_hole
        hole_size: [10, 10]
        hole_center: [5, 5]
    - name: shot_noise
      func: pyxel.models.photon_generation.shot_noise.shot_noise
      enabled: false

  # photon -> photon
  optics:
    - name: alignment
      func: pyxel.models.optics.alignment.alignment
      enabled: true

  # photon -> charge
  charge_generation:

    - name: photoelectrons
      func: pyxel.models.charge_generation.photoelectrons.simple_conversion
      enabled: true

    - name: darkcurrent
      enabled: true
      func: pyxel.models.charge_generation.darkcurrent.darkcurrent_rule07
      

  # charge -> pixel
  charge_collection:

    - name: full_well
      func: pyxel.models.charge_collection.full_well.simple_full_well
      enabled: false
    - name: simple_collection
      func: pyxel.models.charge_collection.collection.simple_collection
      enabled: true

    - name: persistence
      func: pyxel.models.charge_collection.persistence.simple_persistence
      enabled: true
      arguments:
#        trap_density: [5.9e-1, 1.7e-1, 1.5e-1, 1.55e-1, 1.3e-2]
#        trap_timeconstant: [1, 10, 100, 1000, 10000]
        trap_density: [10.]
        trap_timeconstant: [1.]

  # pixel -> signal
  charge_measurement:
    - name: simple_measurement
      func: pyxel.models.charge_measurement.measurement.simple_measurement
      enabled: true
    - name: output_node_noise
      func: pyxel.models.charge_measurement.readout_noise.output_node_noise
      enabled: false
      arguments:
        std_deviation: 5.e-7

  # signal -> image
  readout_electronics:
    - name: simple_amplifier
      func: pyxel.models.readout_electronics.amplification.simple_amplifier
      enabled: true
    - name: simple_digitization
      func: pyxel.models.readout_electronics.digitization.simple_digitization
      enabled: true
      arguments:
        data_type: numpy.uint32
