# ###############
### Pyxel configuration file for CCD detectors
### David Lucsanyi
# ###############

simulation:

  mode: single

  outputs:
    output_folder:  'outputs'
    output_format:

detector:
  class: pyxel.detectors.ccd.CCD

  geometry:
    class: pyxel.detectors.ccd_geometry.CCDGeometry

    row:   100
    col:   100
    total_thickness: 40.    # um
    pixel_vert_size: 10.    # um
    pixel_horz_size: 10.    # um

  material:
    class: pyxel.detectors.material.Material
    material: 'silicon'
    n_acceptor: 0.0               # cm-3
    n_donor: 0.0                  # cm-3

  environment:
    class: pyxel.detectors.environment.Environment
    temperature: 300                     # K

  characteristics:
    class: pyxel.detectors.ccd_characteristics.CCDCharacteristics
    qe: 0.5                 # -
    eta: 0.5                # e/photon
    sv: 1.0e-6              # V/e
    amp: 1.                 # V/V
    a1: 100.                # V/V
    a2: 65536               # DN/V
    fwc: 1000000            # e
    fwc_serial: 1000000     # e
    vg: 1.6200e-10          # cm2
    svg: 1.6200e-10         # cm2
    t: 9.4722e-04           # s
    st: 9.4722e-04          # s

pipeline:
  class: pyxel.pipelines.ccd_pipeline.CCDDetectionPipeline

  # -> photon
  photon_generation:
    - name: load_image
      func: pyxel.models.photon_generation.load_image.load_image
      enabled: false
      arguments:
        image_file: outputs/in.fits
        fit_image_to_det: false
        convert_to_photons: true
    - name: illumination
      func: pyxel.models.photon_generation.illumination.illumination
      enabled: true
      arguments:
          level: 1000
    - name: shot_noise
      func: pyxel.models.photon_generation.shot_noise.shot_noise
      enabled: true

  # photon -> photon
  optics:

  # photon -> charge
  charge_generation:
    - name: photoelectrons
      func: pyxel.models.charge_generation.photoelectrons.simple_conversion
      enabled: true
    - name: tars
      func: pyxel.models.charge_generation.tars.tars.run_tars
      enabled: true
      arguments:
        simulation_mode: cosmic_ray
        running_mode: stepsize
        particle_type: proton
        initial_energy: 100.   # MeV
        particle_number: 10
        incident_angles:      # rad
        starting_position:    # um
        spectrum_file: 'pyxel/models/charge_generation/tars/data/inputs/proton_L2_solarMax_11mm_Shielding.txt'
    - name: charge_injection
      func: pyxel.models.charge_generation.charge_injection.charge_injection
      enabled: false
      arguments:
        input_data_list:

  # charge -> charge
  charge_collection:
    - name: fixed_pattern_noise
      func: pyxel.models.charge_collection.fix_pattern_noise.fix_pattern_noise
      enabled: false
      arguments:
        pix_non_uniformity: data/pixel_non_uniformity.npy
    - name: full_well
      func: pyxel.models.charge_collection.full_well.simple_full_well
      enabled: false
    - name: simple_collection
      func: pyxel.models.charge_collection.collection.simple_collection
      enabled: true

  # charge -> charge
  charge_transfer:
    - name: cdm
      func: pyxel.models.charge_transfer.cdm.cdm
      enabled: true
      arguments:
        parallel_cti: true
        serial_cti: true
        charge_injection: false
        beta_p: 0.3
        beta_s: 0.3
        tr_p: [5.e-3]
        tr_s: [2.e-3]
        nt_p: [100.]
        nt_s: [50.]
        sigma_p: [1.e-15]
        sigma_s: [1.e-15]

  # charge -> signal
  charge_measurement:
    - name: simple_measurement
      func: pyxel.models.charge_measurement.measurement.simple_measurement
      enabled: true
    - name: output_node_noise
      func: pyxel.models.charge_measurement.readout_noise.output_node_noise
      enabled: true
      arguments:
        std_deviation: 5.e-7   # Volt

  # signal -> image
  readout_electronics:
    - name: simple_amplifier
      func: pyxel.models.readout_electronics.amplification.simple_amplifier
      enabled: true
    - name: simple_digitization
      func: pyxel.models.readout_electronics.digitization.simple_digitization
      enabled: false
      arguments:
        data_type: numpy.uint32
    - name: simple_processing
      func: pyxel.models.readout_electronics.digitization.simple_processing
      enabled: true
