################
# Pyxel configuration file for CCD detectors
# David Lucsanyi
################

simulation:
###################
#  mode: single
#  mode: parametric
  mode: calibration
###################

  parametric_analysis:
    parametric_mode: sequential
#    parametric_mode: embedded
    steps:
      -
        enabled: true
  #      key: pipeline.photon_generation.photon_level.arguments.level
        key: pipeline.charge_generation.tars.arguments.particle_number
        values: [2, 3]
      -
        enabled: true
        key: pipeline.photon_generation.photon_level.arguments.level
        values: [1, 2] # todo: list(range(10, 13))

  calibration:
    calibration_mode: pipeline  # single_model
    arguments:
      output: image   # signal # charge
      output_fit_range: [10, 30, 20, 50] #

      target_data_path: ['pyxel/results.fits', 'pyxel/results.fits']     # <*.npy> <*.fits> <ascii>
      target_fit_range: [10, 30, 20, 50]

      fitness_mode: residuals    # least-squares
#      weighting_func_path:  # 'pyxel/results.fits'

      algorithm: sade   # sga  # nlopt
      seed:
#      nlopt_solver: sbplx  # neldermead
      generations: 1
      population_size: 10
      variant: 2

      model_names: ['cdm'] #, 'tars']
      variables: [['tr_p', 'nt_p', 'sigma_p', 'beta_p']]  # , ['initial_energy']]
      var_log: [[True, True, True, False]] #, [False]]
      var_arrays: [[True, True, True, False]] #, [False]]
      params_per_variable: [[4, 4, 4, 1]] #, [1]]
      lower_boundary: [[1.e-3, 1.e-2, 1.e-20, 0.]] #, [1.]]
      upper_boundary: [[2., 1.e+1, 1.e-15, 1.]] #, [10.]]
      sort_by_var: tr_p

#      model: 'cdm'
#        variables: ['tr_p', 'nt_p', 'sigma_p', 'beta_p']
#        var_log: [True, True, True, False]
#        var_arrays: [True, True, True, False]
#        params_per_variable: [4, 4, 4, 1]
#        lower_boundary: [1.e-3, 1.e-2, 1.e-20, 0.]
#        upper_boundary: [2., 1.e+1, 1.e-15, 1.]
#      model: 'tars'
#        variables: ['initial_energy']
#        var_log: [False]
#        var_arrays: [False]
#        params_per_variable: [1]
#        lower_boundary: [1.]
#        upper_boundary: [10.]


processor:
  class: pyxel.pipelines.processor.Processor

  detector:
    class: pyxel.detectors.ccd.CCD

    geometry:
      class: pyxel.detectors.ccd_geometry.CCDGeometry

      row:   100 # 2381 #580 # 4494                   # compulsory
      col:   100 # 2376 #640 # 1966                   # compulsory
      total_thickness: 40.0         # um
      depletion_thickness: 0.0      # um
      field_free_thickness: 0.0     # um
      pixel_vert_size: 10. #10.0         # um
      pixel_horz_size: 10. #10.0  #30.   # um

#      readout_nodes: 1    # channels
#      image_area:
#        row:   5
#        col:   10
#      parallel_overscan:
#        type: physical  # virtual
#        row:   3
#        col:   10
#      serial_underscan:
#        type: physical  # virtual
#        row:   8
#        col:   2
#      serial_overscan:
#        type: physical  # virtual
#        row:   8
#        col:   4

    material:
      class: pyxel.detectors.material.Material
      material: 'silicon'
#      compound: 'silicon'
#        element: 'silicon'
#        ratio: 1.
      n_acceptor: 0.0               # cm-3
      n_donor: 0.0                  # cm-3

    environment:
      class: pyxel.detectors.environment.Environment
      temperature: 300                     # K
#      total_ionising_dose: 0              #
#      total_non_ionising_dose: 0          #

    characteristics:
      class: pyxel.detectors.ccd_characteristics.CCDCharacteristics
      qe: 0.5                 # -
      eta: 0.5                # e/photon
      sv: 1.0e-6              # V/e
      amp: 1.                 # V/V
      a1: 100                 # V/V
      a2: 65536               # DN/V
      fwc: 1.e6               # e
      fwc_serial: 1.e6        # e
      vg: 1.6200e-10          # cm2
      svg: 1.6200e-10         # cm2
      t: 9.4722e-04           # s
      st: 9.4722e-04          # s
#      bias_voltage: 0.0        # V

  pipeline:
    class: pyxel.pipelines.ccd_pipeline.CCDDetectionPipeline

    # -> photons
    photon_generation:
      -
        name: load_image
        func: pyxel.models.photon_generation.load_image
        enabled: true
        arguments:
          image_file: data/01.fits
          row0: 0
          col0: 0
          rows: 100
          cols: 100
      -
        name: photon_level
        func: pyxel.models.photon_generation.add_photon_level
        enabled: false
        arguments:
          level: 0
      -
        name: shot_noise
        func: pyxel.models.photon_generation.add_shot_noise
        enabled: false

    # photons -> photons
    optics:

    # photons -> charge
    charge_generation:
      -
        name: charge_injection
        func: pyxel.models.charge_injection.charge_injection
        enabled: false
        arguments:
          input_data_list: #path
      -
        name: photoelectrons
        func: pyxel.models.photoelectrons.simple_conversion
        enabled: true
      -
        name: tars
        func: pyxel.models.tars.tars.run_tars
        enabled: false
        arguments:
          simulation_mode: cosmic_ray   # snowflakes
          running_mode: stepsize  # stopping  # plotting  # geant4
          particle_type: proton
          initial_energy: 100.   # MeV
          particle_number: 1
          incident_angles:      # rad
          starting_position:    # um
          spectrum_file: 'pyxel/models/tars/data/inputs/proton_L2_solarMax_11mm_Shielding.txt'

    # charge -> charge
    charge_collection:
      -
        name: fixed_pattern_noise
        func: pyxel.models.ccd_noise.add_fix_pattern_noise
        enabled: false
        arguments:
          pix_non_uniformity: data/non_uniformity_array_normal_random_dist.data
      -
        name: full_well
        func: pyxel.models.full_well.simple_pixel_full_well
        enabled: false

    # charge -> charge
    charge_transfer:
      -
        name: cdm
        func: pyxel.models.cdm.CDM.cdm
        enabled: true
        arguments:
         beta_p: 0.1  # _
         beta_s: 0.3
         parallel_cti: true
         serial_cti: false
         chg_inj: true
         para_transfers: 1552
         tr_p: [0.01] # _
         tr_s: [0.01]
         nt_p: [1.] # _
         nt_s: [1.]
         sigma_p: [1.] # _
         sigma_s: [1.]
#         parallel_trap_file: pyxel/models/cdm/cdm_euclid_parallel.dat
#         serial_trap_file: pyxel/models/cdm/cdm_euclid_serial.dat

    # charge -> signal
    charge_measurement:
      -
        name: output_node_noise
        func: pyxel.models.ccd_noise.add_output_node_noise
        enabled: false
        arguments:
          std_deviation: 40.

    # signal -> image
    readout_electronics: