################
# Pyxel configuration file for CMOS detectors
# Used and modified by David
################

simulation:

#  mode: single

  mode: dynamic
  dynamic:
    non_destructive_readout:  true
    steps: 6
    t_step: 2.1

  outputs:
    output_folder:  outputs
    save_to_file:
      - detector.image.array:   [fits, png]
      - detector.signal.array:  [npy, txt]
      - detector.charge.frame:  [csv]
#      - detector.photon.array:
      - detector:               [hdf]

cmos_detector:

  geometry:
    row: 100                      # pixels
    col: 100                      # pixels
    total_thickness: 10.         # um
    pixel_vert_size: 10.         # um
    pixel_horz_size: 10.         # um
    n_output: 1
    n_row_overhead: 0
    n_frame_overhead: 0
    reverse_scan_direction: False
    reference_pixel_border_width: 4

  material:
    material: silicon

  environment:
    temperature: 300                     # K

  characteristics:
    qe: 0.5               # -
    eta: 1                # e/photon
    sv: 1.0e-6            # V/e
    amp: 0.8              # V/V
    a1: 100               # V/V
    a2: 65536             # DN/V
    fwc: 20000            # e

pipeline:

  # photon -> photon
  photon_generation:
    - name: load_image
      func: pyxel.models.photon_generation.load_image.load_image
      enabled: true
      arguments:
        image_file: data/fits/Pleiades_HST.fits
        fit_image_to_det: true
        convert_to_photons: true

    - name: illumination
      func: pyxel.models.photon_generation.illumination.illumination
      enabled: true
      arguments:
        level: 2000

    - name: shot_noise
      func: pyxel.models.photon_generation.shot_noise.shot_noise
      enabled: false

  # photon -> photon
  optics:

  # photon -> charge
  charge_generation:
    - name: photoelectrons
      enabled: true
      func: pyxel.models.charge_generation.photoelectrons.simple_conversion

  # charge -> charge
  charge_collection:
    - name: full_well
      func: pyxel.models.charge_collection.full_well.simple_full_well
      enabled: false

    - name: simple_collection
      func: pyxel.models.charge_collection.collection.simple_collection
      enabled: true

  # charge -> signal
  charge_measurement:
    - name: nghxrg
      func: pyxel.models.charge_measurement.nghxrg.nghxrg.nghxrg
      enabled: true
      arguments:
        pca0_file: pyxel/models/charge_measurement/nghxrg/nirspec_pca0.fits
        window_position: [10, 10]
        window_size: [50, 50]
        noise:
          - ktc_bias_noise: true
            ktc_noise: 29.
            bias_offset: 5000.
            bias_amp: 500.
          - white_read_noise: true
            rd_noise: 40.
            ref_pixel_noise_ratio: 8.
          - corr_pink_noise: true
            c_pink: 30.
          - uncorr_pink_noise: true
            u_pink: 20.
          - acn_noise: true
            acn: 50.
          - pca_zero_noise: true
            pca0_amp: 45.

    - name: simple_measurement
      func: pyxel.models.charge_measurement.measurement.simple_measurement
      enabled: true

  # signal -> signal
  signal_transfer:

  # signal -> image
  readout_electronics:
    - name: simple_amplifier
      func: pyxel.models.readout_electronics.amplification.simple_amplifier
      enabled: true

    - name: simple_processing
      func: pyxel.models.readout_electronics.digitization.simple_processing
      enabled: true

