################
# Pyxel configuration file for CCD detectors
# Used and modified by David
################

parametric:
  mode: single
#  mode: embedded
#  mode: sequential
  steps:
    -
      enabled: false
      key: pipeline.photon_generation.photon_level.arguments.level
      values: [10, 20, 30]
    -
      enabled: false
      key:
      values:
    -
      enabled: false
      key:
      values:
    -
      enabled: false
      key:
      values:

processor:
  class: pyxel.pipelines.processor.Processor

  detector:
    class: pyxel.detectors.ccd.CCD

    geometry:
      class: pyxel.detectors.ccd_geometry.CCDGeometry
      row:   4494                   # compulsory
      col:   1966                   # compulsory
      total_thickness: 40.0         # um
      depletion_thickness: 0.0      # um
      field_free_thickness: 0.0     # um
      pixel_vert_size: 10.0         # um
      pixel_horz_size: 30.0         # um

    material:
      class: pyxel.detectors.material.Material
      material: 'silicon'
#      compound: 'silicon'
#        element: 'silicon'
#        ratio: 1.
      n_acceptor: 0.0               # cm-3
      n_donor: 0.0                  # cm-3

    environment:
      class: pyxel.detectors.environment.Environment
      temperature: 300                     # K
#      total_ionising_dose: 0              #
#      total_non_ionising_dose: 0          #

    characteristics:
      class: pyxel.detectors.ccd_characteristics.CCDCharacteristics
      qe: 0.5               # -
      eta: 1                # e/photon
      sv: 1.0e-6            # V/e
      amp: 0.8              # V/V
      a1: 100               # V/V
      a2: 65536             # DN/V
      fwc: 20000            # e
      fwc_serial: 30000     # e
#      bias_voltage: 0.0             # V

  pipeline:
    class: pyxel.pipelines.ccd_pipeline.CCDDetectionPipeline

    # -> photons
    photon_generation:
      -
        name: load_image
        func: pyxel.models.photon_generation.load_image
        enabled: false
        arguments:
          image_file: null
      -
        name: photon_level
        func: pyxel.models.photon_generation.add_photon_level
        enabled: true
        arguments:
          level: 0
      -
        name: shot_noise
        func: pyxel.models.photon_generation.add_shot_noise
        enabled: false

    # photons -> photons
    optics:

    # photons -> charge
    charge_generation:
      -
        name: photoelectrons
        enabled: false
        func: pyxel.models.photoelectrons.simple_conversion
      -
        name: tars
        func: pyxel.models.tars.tars.run_tars
        enabled: true
        arguments:
          simulation_mode: cosmic_ray   # snowflakes
          running_mode: plotting  # stepsize  # stopping  # plotting  # geant4
          particle_type: proton
          initial_energy: random   # MeV
          particle_number: 1000
          incident_angles:      # rad
#            - 0.31415 # pi / 4
#            - 3.1415  # 0 # 1.570 # 3.1415 # 2.094 # pi / 2
          starting_position:    # um
#            - 10. #500.0  # vertical
#            - 20. #500.0  # horizontal
#            - 0.0         # z
          spectrum_file: 'pyxel/models/tars/data/inputs/proton_L2_solarMax_11mm_Shielding.txt'

    # charge -> charge
    charge_collection:
      -
        name: fixed_pattern_noise
        enabled: false
        func: pyxel.models.ccd_noise.add_fix_pattern_noise
        arguments:
          pix_non_uniformity: data/non_uniformity_array_normal_random_dist.data
      -
        name: full_well
        func: pyxel.models.full_well.simple_pixel_full_well
        enabled: false

    # charge -> charge
    charge_transfer:
      -
        name: cdm
        enabled: false
        func: pyxel.models.cdm.CDM.cdm
        arguments:
         beta_p: 0.6
         beta_s: 0.6
         vg: 6.e-11
         svg: 1.0e-10
         t: 20.48e-3
         st: 5.0e-6
         parallel_trap_file: pyxel/models/cdm/cdm_euclid_parallel.dat
         serial_trap_file: pyxel/models/cdm/cdm_euclid_serial.dat

    # charge -> signal
    charge_measurement:
      -
        name: output_node_noise
        enabled: false
        func: pyxel.models.ccd_noise.add_output_node_noise
        arguments:
          std_deviation: 1.0

    # signal -> image
    readout_electronics: