################
# Pyxel configuration file for TESTING, EXPERIMENTING
# David Lucsanyi
################

simulation:
 mode: single
# mode: parametric

 parametric:
#   parametric_mode: parallel
#   parametric_mode: embedded
   parametric_mode: sequential
   parameters:
     - key: pipeline.photon_generation.illumination.arguments.level
       values: numpy.unique(numpy.logspace(3, 6, 10, dtype=int))
     - key: detector.characteristics.sv
       values: numpy.unique(numpy.linspace(1.e-6, 1.e-3, 10, dtype=float))

 outputs:
   output_folder:  'outputs'

   save_data_to_file:         # ONLY IN SINGLE MODE
     - detector.image.array:   [fits]
     - detector.signal.array:  [npy, txt]
     - detector.charge.frame:  [csv]
     - detector:               [hdf]

   save_parameter_to_file:    # ONLY IN PARAMETRIC MODE
     file_format:              [txt, npy, csv]
     parameter:
       - detector.image.mean
       - detector.image.std_deviation
       - pipeline.photon_generation.illumination.arguments.level

   parametric_plot:
#     x:  'detector.characteristics.sv'
##     x:  'pipeline.photon_generation.illumination.arguments.level'
     x:  'detector.image.mean'
     y:  'detector.image.std_deviation'
     plot_args:
       title: 'Curve'
       xscale: 'log'
       yscale: 'log'
#       xlim: [1., 2.e+6]
#       ylim: [1., 3.e+4]
       grid: true

ccd_detector:

  geometry:
    row:   100                   #
    col:   100                   #
    total_thickness: 40.         # um
    pixel_vert_size: 10.         # um
    pixel_horz_size: 10.         # um

  material:
    material: silicon

  environment:
    temperature: 300.

  characteristics:
    qe: 0.5                 # -
    eta: 1.                 # e/photon
    sv: 3e-6                # V/e
    amp: 10.                # V/V
    a1: 100.                # V/V
    a2: 100                 # DN/V
    fwc: 1000000            # e
    fwc_serial: 1000000     # e
    vg: 1.6200e-10          # cm2
    svg: 1.6200e-10         # cm2
    t: 9.4722e-04           # s
    st: 9.4722e-04          # s

pipeline:

  # photon -> photon
  photon_generation:
    - name: load_image
      func: pyxel.models.photon_generation.load_image.load_image
      enabled: false
      arguments:
        image_file: data/fits/HorseHead.fits
        fit_image_to_det: true
        convert_to_photons: true
    - name: illumination
      func: pyxel.models.photon_generation.illumination.illumination
      enabled: true
      arguments:
          level: 1111
          option: elliptic_hole
          hole_size: [20, 10]
          hole_center: [50, 50]
    - name: shot_noise
      func: pyxel.models.photon_generation.shot_noise.shot_noise
      enabled: true

  # photon -> photon
  optics:
    - name: optical_psf
      func: pyxel.models.optics.poppy.optical_psf
      enabled: false
      arguments:
        fov_pixels: 30       # FOV in pixel
        pixelscale: 0.1      # micron/pixel OR arcsec/pixel
        wavelength: 2.e-6    # wavelength in microns
        # fov_arcsec = 10.   # FOV in arcsec, do not use this
        optical_system:
          - item: CircularAperture
            radius: 1.5
          - item: ThinLens
            radius: 1.2
            nwaves: 1
          - item: ZernikeWFE
            radius: 0.8
            coefficients: [0.1e-6, 3.e-6, -3.e-6, 1.e-6, -7.e-7, 0.4e-6, -2.e-6]
            aperture_stop: false

    - name: alignment
      func: pyxel.models.optics.alignment.alignment
      enabled: false

  # photon -> charge
  charge_generation:

    - name: photoelectrons
      func: pyxel.models.charge_generation.photoelectrons.simple_conversion
      enabled: true
    - name: charge_injection
      func: pyxel.models.charge_generation.charge_injection.charge_blocks
      enabled: false
      arguments:
        charge_level: 1230
        columns: [30, 50, 60]
    - name: tars
      func: pyxel.models.charge_generation.tars.tars.run_tars
      enabled: false
      arguments:
        simulation_mode: cosmic_ray
        running_mode: stepsize
        particle_type: proton
        initial_energy: 100.   # MeV
        particle_number: 2
        incident_angles:      # rad
        starting_position:    # um
        spectrum_file: pyxel/models/charge_generation/tars/data/inputs/proton_L2_solarMax_11mm_Shielding.txt

  # charge -> pixel
  charge_collection:
    - name: fixed_pattern_noise
      func: pyxel.models.charge_collection.fix_pattern_noise.fix_pattern_noise
      enabled: true
      arguments:
        pixel_non_uniformity: data/pixel_non_uniformity.npy
    - name: full_well
      func: pyxel.models.charge_collection.full_well.simple_full_well
      enabled: false
    - name: simple_collection
      func: pyxel.models.charge_collection.collection.simple_collection
      enabled: true

  # pixel -> pixel
  charge_transfer:
#    - name: cdm
#      func: pyxel.models.charge_transfer.cdm.cdm
#      enabled: true
#      arguments:
#        parallel_cti: true
#        serial_cti: true
#        charge_injection: false
#        beta_p: 0.3
#        beta_s: 0.3
#        tr_p: [5.e-2]
#        tr_s: [2.e-2]
#        nt_p: [100.]
#        nt_s: [50.]
#        sigma_p: [1.e-15]
#        sigma_s: [1.e-15]

  # pixel -> signal
  charge_measurement:
    - name: simple_measurement
      func: pyxel.models.charge_measurement.measurement.simple_measurement
      enabled: true
    - name: output_node_noise
      func: pyxel.models.charge_measurement.readout_noise.output_node_noise
      enabled: true
      arguments:
        std_deviation: 5.e-5

  # signal -> image
  readout_electronics:
    - name: simple_amplifier
      func: pyxel.models.readout_electronics.amplification.simple_amplifier
      enabled: true
    - name: simple_digitization
      func: pyxel.models.readout_electronics.digitization.simple_digitization
      enabled: true
      arguments:
        data_type: numpy.uint32
